language: node_js
sudo: false
node_js:
  - "0.12"
  - "4.2"
  - "5.1"
before_install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libyajl-dev
    - libxml2-dev
    - gcc-4.8
    - g++-4.8
branches:
  only:
    - master
